export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const IS_LOGGED_IN = 'IS_LOGGED_IN'
export const FETCH_SONG = 'FETCH_SONG'
export const PLAYER_READY = 'PLAYER_READY'
export const QUIZ_SELECTED = 'QUIZ_SELECTED'
export const FETCH_POSSIBLE_QUIZZES = 'FETCH_POSSIBLE_QUIZZES'
export const QUIZ_STARTED = 'QUIZ_STARTED'
export const FETCH_QUESITONS = 'FETCH_QUESITONS'

